### ISSUE TITLE
Afte Show Connected Nothing changed 

### ISSUE THREAD

**Issue by Mohammadshamchi** [amircloner/tcp-vpn-proxy#2]
سلام امیر عزیز 
امیدوارم حالت خوب باشه 
ممنون که تو این اوضاع کمکمون میکنی 
من تقریبا تمامی مراحل رو رفتم متاسفانه بعد کانکت شدن به هیچ عنوان چیزی آپدیت نمیشه 
و بعضا موقع وارد کردن لینک ss 
مثال : 
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTozNTMzODI=@[domain.com:443?plugin=v2ray%3Bpath%3D%2Fv2%3Bhost%3Ddomain.com%3Btls](http://domain.com:443/?plugin=v2ray%3Bpath%3D%2Fv2%3Bhost%3Ddomain.com%3Btls) 

میگه فرمت درست نیست با qr code هم اسکن میکنم import میشه اما همچنان بعد کانکت شدن نمیشه دسترسی به اینترنت داشت

**Comment by amircloner** [comment]
سلام محمد عزیز
نیاز به اطلاعات بیشتری دارم
از قبیل لاگ های کلاینت و سرور

چند نکته را در نظر داشته باش :
1- اطمینان داشته باش که پورت های 80 و 443 در سرور خارج از کشور باز باشد
2- بامشاهده وضعیت کانتینر داکر از سالم بود up بودن کانتینر اطمینان حاصل کن
3- پروتکل ارتباطی سرور و ابرآروان را در حالت HTTP قرار بده
4- کلاینت را هم با اینترنت موبایل و هم با اینترنت adsl چک کن
5- از کلاینت هایی که در Readme ریپو ذکر شده استفاده کن
