### ISSUE TITLE
Question about server

### ISSUE THREAD

**Issue by sasanaskari** [amircloner/tcp-vpn-proxy#3]
Are all your docker files running on an external server?

**Comment by amircloner** [comment]
Yes , you don't need to internal server

**Comment by sasanaskari** [comment]
And also I want to know how to change main page that redirect to your github app and change qr page!it's a security issue!

**Comment by sasanaskari** [comment]
I have access to the qr page and Docker is running on my server! Arvan's dig command returns the CDN, but I sent bits in my v2ray program and I don't receive any bits! My server has access to the Internet!I use Shadowsocks!

**Comment by amircloner** [comment]
Please check issue link below
#1

**Comment by sasanaskari** [comment]
> Please check issue link below #1

Thanks! I am checking it! So what is your solution for other issues I have said?

**Comment by amircloner** [comment]
If issue was mentioned no help

1. check proxy connectivity with Mobile Network and ADSL
2. send docker container logs

**Comment by sasanaskari** [comment]
Here's what I mean about redirecting to your git profile and changing QR code page!

**Comment by amircloner** [comment]
> And also I want to know how to change main page that redirect to your github app and change qr page!it's a security issue!

fork project edit and customize source code

**Comment by alemsas** [comment]
thanks I have changed those things that I want!
