### ISSUE TITLE
چرایی نمایش محتویات صفحه گیت هاب روی دامنه

### ISSUE THREAD

**Issue by mehdinmo** [amircloner/tcp-vpn-proxy#6]
سلام
لطفا راه عدم نمایش  محتویات صفحه گیت هاب روی دامنه  را بگویید!

**Comment by amircloner** [comment]
از پروژه fork بگیرید
در فایل
/conf/nginx_ss.conf

```
    location = / {
    proxy_pass https://github.com/amircloner;
    }
```
به جای https://github.com/amircloner یک آدرس را وارد نمایید
